version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: backend-starter
    main: ./    
    binary: backend-starter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: backend-starter
    tap:
      owner: Walon-Foundation
      name: homebrew-tap  
    commit_author:
      name: CI Bot
      email: ci@example.com
    description: "A backend starter CLI written in Go"
    homepage: "https://github.com/Walon-Foundation/backend-starter-cli"

release:
  github:
    owner: Walon-Foundation  
    name: backend-starter-cli
