version: 2

project_name: backend-starter

checksum:
  disable: true

changelog:
  disable: true

before:
  hooks:
    - go mod tidy
    - go generate ./...


builds:
  - id: mac-build
    binary: backend-starter
    main: ./main.go   
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

  - id: linux-build
    binary: backend-starter
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

  - id: windows-build
    binary: backend-starter
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath

archives:
  - id: mac-archive
    builds: [mac-build]
    name_template: "backend-starter_{{ .Version }}_macOS_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - none*

  - id: linux-archive
    builds: [linux-build]
    name_template: "backend-starter_{{ .Version }}_linux_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - none*

  - id: windows-archive
    builds: [windows-build]
    name_template: "backend-starter_{{ .Version }}_windows_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - none*


brews:
  - name: backend-starter
    ids:
      - mac-archive
    repository:
      owner: Walon-Foundation
      name: homebrew-tap
    homepage: "https://github.com/Walon-Foundation/backend-starter-cli"
    license: Apache-2.0


release:
  mode: keep-existing
  replace_existing_artifacts: true
  github:
    owner: Walon-Foundation
    name: backend-starter-cli
